//number 
let x = 10;

//string 
let a = "Ashlesha";

// boolean
let b = true;

//null
let c = null;

//undefined -- two ways of writing undefined variable

let age = undefined;

// bigInt -- TO STORE A VERY BIG INTEGER OR NUMBER 
let salary = BigInt (4889546845698595958945541557);

// symbol 
let value = Symbol("123");

// object -- non-primitive
const user = {name: "Ashlesha", age: 23};

//array -- it is a type of object , we can put multiple value to an variable is called as array
const fruits = ["mango", "apple", "banana"];

// typeof operator 
console.log(typeof(x));